### PR TITLE
TNT-40793, TNT-40657 - Regenerate openapi models

### PR DESCRIPTION
**Pull request by dcottingham**
Regenerated openapi models to include several recent updates.  It looks like there are potentially breaking changes in here due to types in some models being updated.  I can remove them if we think they are unnecessary, or we could do a major version bump next release.

Side Note:  The openapi-generator-cli that we use for the other SDKs is pinned to an older version of the typescript-fetch generator, which seems to be a problem.  The pinned version results in slightly incorrect models, so I used a workaround.  We can discuss and if agreed upon I will update the README.  At this point in time we won't be able keep the openapi client generation in-sync with the other SDKs because of this.

### CODE REVIEW

**Comment by artur-ciocanu** [comment]
@dcottingham overall it looks, however I am not sure which breaking changes are you referring to. Is it `Parameters` and `TraceResponse` or something else?

**Review by XDex — APPROVED** [review]
@dcottingham Looks good, I'm not sure replacing Oneof... types with actual TS union types should break anything, it's actually much better to have union types than the old custom types..

**Comment by dcottingham** [comment]
> @dcottingham Looks good, I'm not sure replacing Oneof... types with actual TS union types should break anything, it's actually much better to have union types than the old custom types..

@XDex, Agreed it is definitely better.  But I'm not sure if customers are using these TS interfaces explicitly in their code.  If they are then they will have some very minor changes to make since we removed the Oneof... types.  That's the only change that isn't fully backward compatible.  And if customers are not explicitly using the Oneof... type then they won't even notice a difference.

CC: @artur-ciocanu

**Review by artur-ciocanu — APPROVED** [review]
Looks good to me.

**Pull request merged**
