### PR TITLE
TNT-42984 - regenerate openapi models and handling for telemetryServerToken

### PR DESCRIPTION
**Pull request by dcottingham**
Delivery API request and response have been updated to include new fields to support telemetry data collected on Edge.  The openapi models should be updated accordingly.

Spec: 
https://wiki.corp.adobe.com/display/testntarget/%5Bspec%5D+Add+telemetry+data+to+Delivery+API+response+for+usage+in+SDKs
The backend change that supports this will not get released until Jan. 2022.  We should not release this change until after the backend in order to avoid potential issues during the backend rolling deployment process.

Note:  This PR includes several openapi model updates that aren't related to telemetry, but were things updated recently in order to make sure our spec adheres to OpenApi 3.0 spec.  None of these represent functional changes that require updates in other parts of the code.  I've tested a few scenarios in localdev to verify E2E functionality.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jasonwaters — COMMENTED** [review]
left a few comments for you.  Not sure if you intended to remove some properties from  request objects...?

**Comment by dcottingham** [comment]
> left a few comments for you. Not sure if you intended to remove some properties from request objects...?

@jasonwaters - this was intentional, as now all those types are pulling several properties from their parent type via type inheritance.  Our openapi spec was actually incorrect before, which is why there was no type inheritance and lots of repeated properties.  Functionality for the updated types remain the same.

**Comment by jasonwaters** [comment]
@dcottingham which parent class/interface has the properties now?

**Comment by dcottingham** [comment]
> @dcottingham which parent class/interface has the properties now?

`RequestDetails` and `MboxResponse`.  For example, `export interface PrefetchMboxResponse extends MboxResponse`

**Review by jasonwaters — APPROVED** [review]

**Comment by jasonwaters** [comment]
gotcha, thanks for the explanation.  LGTM

**Pull request merged**
